### ISSUE TITLE
Frage: Wie wechselt man den in den "Expertenmodus"?

### ISSUE THREAD

**Issue by odo2063** [letsgoING/ArduBlock2#1]
Wie wechselt man den in den "Expertenmodus"?

**Comment by letsgoING** [comment]
Über den Button "Projekt Blöcke" / "Grundlagen Blöcke" unten rechts.

**Comment by odo2063** [comment]
Zur Info...Dazu muss man das Fenster breit genug machen sonst ist dieser Button nicht sichtbar und nicht "erscrollbar" ;-)
