### ISSUE TITLE
Expertenmodus funktioniert nicht unter Linux

### ISSUE THREAD

**Issue by erniberni** [letsgoING/ArduBlock2#3]
Ein Wechseln in den Expertenmodus ist unter Linux nicht möglich. Weder der Durck auf den Button noch ctrl-b hat eine Reaktion.

**Comment by quizilkend** [comment]
Habe dieses Verhalten zuerst ebenfalls festgestellt, es liegt aber daran, dass das Fenster nicht groß genug eingestellt ist. Jetzt komme ich in den Expertenmodus.
Siehe https://github.com/letsgoING/ArduBlock2/issues/1

Ich denke, man könnte den Issue schließen. Allerdings wäre ein Hinweis im Readme.md super.

**Comment by letsgoING** [comment]
Das Problem sollte nun behoben sein.
